### ISSUE TITLE
Dependabot having trouble opening PRs for security-related issues because it can't authenticate into Gemfury

### ISSUE THREAD

**Issue by andrew-p-morris-er** [EntityRisk/.github#22]
Not sure if this is the right place for this, but in deployment repositories like `syn23a-cve` (example below), dependabot-detected security issues are recognized, but PRs to address them can't be opened because it can't get into gemfury for dependency resolution: https://github.com/EntityRisk/syn23a-cve/security/dependabot/34

Note:
- I believe the workflows on this repo and the others affected are up to date
- Unfortunately, attempting a "Try again" has not helped

![image](https://github.com/EntityRisk/.github/assets/97974936/6e25e276-7833-4697-84b9-a4fd2395bbd6)

**Comment by andrew-p-morris-er** [comment]
I now realize (perhaps this was obvious to you, @jeff-m-sullivan ) that this could be related to the general issue that crops up when installing gemfury deps using poetry 1.8: https://github.com/EntityRisk/infrastructure/issues/110

However, I can't quite figure out where, in this context, we would specify `poetry==1.7` to try that out as a fix...any ideas?

**Comment by jeff-m-sullivan** [comment]
It has actually fixed itself. If you check that alert, the reason it cannot currently generate the PR is because one of the dependencies has requirements that prevent the upgrade.

**Comment by andrew-p-morris-er** [comment]
ah, I see - got it.  thanks @jeff-m-sullivan for clearing that up; good news!
