### ISSUE TITLE
Is there a way to run `codecov` prior to marking a PR as "ready for review"

### ISSUE THREAD

**Issue by andrew-p-morris-er** [EntityRisk/.github#6]
Basically title and hopefully a quick question for you, @jeff-m-sullivan - just wondering in case I am able to do a bit more self-checking prior to marking things as ready for review.  Will help with situations like[ this one](https://github.com/EntityRisk/erutils/pull/18), where had I checked it, the review request would've been less confusing.

Thanks!

**Comment by jeff-m-sullivan** [comment]
You can always check for coverage locally:

```
(erutils-py3.9) ➜  erutils git:(main) python -m pytest --cache-clear --cov=erutils tests

```

After going through all the tests, will give you:

```
---------- coverage: platform darwin, python 3.9.15-final-0 ----------
Name                     Stmts   Miss  Cover
--------------------------------------------
erutils/__init__.py          6      0   100%
erutils/_data.py             4      0   100%
erutils/_sql.py             41      0   100%
erutils/_stats.py           33      0   100%
erutils/_strings.py         26      0   100%
erutils/_validation.py     137      2    99%
erutils/plotting.py          2      0   100%
--------------------------------------------
TOTAL                      249      2    99%
```

The check in CI will fail if coverage goes down as compared to the branch being merged into.

**Comment by jeff-m-sullivan** [comment]
If you want to look line-by-line to find the misses, you can generate a human-readable HTML report:

```
python -m pytest --cache-clear --cov=erutils --cov-report=html tests
```

**Comment by jeff-m-sullivan** [comment]
Was this sufficient, or do you need a GitHub Actions solution?

**Comment by andrew-p-morris-er** [comment]
Apologies - this was perfect, thanks Jeff!
